# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MesadaInteligente' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MesadaInteligente
  pod 'M13Checkbox'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod "SACountingLabel"


end
